[package]
name = "aviation_calc_util_ffi"
version = "2.0.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
aviation_calc_util = "2.0.0"
paste = "1.0.14"

[build-dependencies]
cbindgen = "0.26.0"
